● Создайте случайную матрицу А1 размерностью 5 на 5

● Транспонируйте матрицу A1

● Найдите обратную матрицу для А1

● Создайте диагональную матрицу - поэлементно перемножив единичную
матрицу I и случайную матрицу A2 размерности 4 на 4

● Создайте нулевую матрицу размерности 3 на 3

● Для всех полученных матриц найдите: определитель, ранг и собственные
значения

● Проанализируйте результаты

In [11]:
import numpy as np

A1 = np.random.random([5,5])
A1

array([[0.52417436, 0.66433111, 0.03303538, 0.09937226, 0.84214832],
       [0.61942255, 0.57281404, 0.38034659, 0.76815126, 0.52274333],
       [0.51152041, 0.7585552 , 0.94752027, 0.05035935, 0.2910821 ],
       [0.17601496, 0.94128278, 0.92437283, 0.54876355, 0.50899907],
       [0.88126413, 0.71679703, 0.37249083, 0.21893924, 0.84781171]])

In [12]:
A1.T

array([[0.52417436, 0.61942255, 0.51152041, 0.17601496, 0.88126413],
       [0.66433111, 0.57281404, 0.7585552 , 0.94128278, 0.71679703],
       [0.03303538, 0.38034659, 0.94752027, 0.92437283, 0.37249083],
       [0.09937226, 0.76815126, 0.05035935, 0.54876355, 0.21893924],
       [0.84214832, 0.52274333, 0.2910821 , 0.50899907, 0.84781171]])

In [14]:
np.linalg.inv(A1)

array([[ 0.57562665,  1.53202052,  1.71575521, -2.05947546, -0.86902674],
       [ 6.74013136,  3.49834741,  4.79134197, -3.11534524, -8.62679068],
       [-4.37360279, -2.53917945, -2.23314137,  2.48192489,  5.18663678],
       [-0.4212806 ,  1.27664025, -0.66486122,  0.30057325, -0.32086927],
       [-4.26654108, -3.76428554, -4.68153989,  3.60659154,  7.18057586]])

In [39]:
I = np.eye(4)
A2 = np.random.random([4,4])
I*A2

array([[0.23166416, 0.        , 0.        , 0.        ],
       [0.        , 0.57312588, 0.        , 0.        ],
       [0.        , 0.        , 0.37242353, 0.        ],
       [0.        , 0.        , 0.        , 0.92363011]])

In [22]:
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
print(np.linalg.det(A1))
print(np.linalg.matrix_rank(A1))
print(np.linalg.eig(A1))

-0.03666046063903341
5
(array([ 2.73094504, -0.42290965,  0.66369538,  0.1495496 ,  0.31980356]), array([[-0.35515394, -0.52743028,  0.40163394, -0.04233403, -0.12988101],
       [-0.47093061,  0.68784001, -0.39981233, -0.66118698,  0.60222292],
       [-0.39549599, -0.19096705, -0.00889601,  0.46937903, -0.43558762],
       [-0.51202685, -0.44715563, -0.68165594, -0.20569708,  0.44826551],
       [-0.48321989,  0.11080092,  0.46271625,  0.54627066, -0.47935367]]))


In [32]:
print(np.linalg.det(A1.T))
print(np.linalg.matrix_rank(A1.T))
print(np.linalg.eig(A1.T))

-0.03666046063903334
5
(array([ 2.73094504, -0.42290965,  0.66369538,  0.31980356,  0.1495496 ]), array([[ 0.46602857,  0.63464142, -0.19127532, -0.18139506, -0.34999074],
       [ 0.56226708, -0.52192226,  0.12506917, -0.18663305, -0.27921873],
       [ 0.37648565, -0.06347074,  0.79048455, -0.72563457, -0.55688172],
       [ 0.27777564,  0.4332027 , -0.05961998,  0.36595113,  0.36849462],
       [ 0.49776737, -0.36487574, -0.56511158,  0.52134267,  0.59467458]]))


In [33]:
print(np.linalg.det(np.linalg.inv(A1)))
print(np.linalg.matrix_rank(np.linalg.inv(A1)))
print(np.linalg.eig(np.linalg.inv(A1)))

-27.277344107762573
5
(array([ 6.68674456, -2.36457122,  3.12691953,  0.36617361,  1.50671533]), array([[-0.04233403, -0.52743028, -0.12988101, -0.35515394,  0.40163394],
       [-0.66118698,  0.68784001,  0.60222292, -0.47093061, -0.39981233],
       [ 0.46937903, -0.19096705, -0.43558762, -0.39549599, -0.00889601],
       [-0.20569708, -0.44715563,  0.44826551, -0.51202685, -0.68165594],
       [ 0.54627066,  0.11080092, -0.47935367, -0.48321989,  0.46271625]]))


In [40]:
print(np.linalg.det(I))
print(np.linalg.matrix_rank(I))
print(np.linalg.eig(I))

1.0
4
(array([1., 1., 1., 1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [42]:
print(np.linalg.det(I*A2))
print(np.linalg.matrix_rank(I*A2))
print(np.linalg.eig(I*A2))

0.045671371143475845
4
(array([0.23166416, 0.57312588, 0.37242353, 0.92363011]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [34]:
print(np.linalg.det(z))
print(np.linalg.matrix_rank(z))
print(np.linalg.eig(z))

0.0
0
(array([0., 0., 0.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
